//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarEvents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoyaltyPoint
    {
        public int LoyaltyId { get; set; }
        public int UserId { get; set; }
        public string TransactionType { get; set; }
        public int Points { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> RelatedOrderId { get; set; }
        public string Status { get; set; }
    
        public virtual User User { get; set; }
    }
}
