//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarEvents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizerProfile
    {
        public int OrganizerId { get; set; }
        public string OrganizationName { get; set; }
        public string ContactPerson { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public string ProfilePhoto { get; set; }
    
        public virtual User User { get; set; }
    }
}
