//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarEvents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int TicketId { get; set; }
        public int BookingId { get; set; }
        public int SeatCategoryId { get; set; }
        public string TicketCode { get; set; }
        public string QRCodePath { get; set; }
        public Nullable<bool> IsUsed { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual SeatCategory SeatCategory { get; set; }
    }
}
